use_frameworks!

#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/wenchao8023/CwenSpec.git'


platform :ios, '10.0'

target 'OCRepo_Example' do
  pod 'XYLog', :path => '../Packages/XYLog'
  pod 'XYWeb', :path => '../Packages/XYWeb'
  pod 'ManagerBook'
  pod 'MotivationalBook'
end
